services:
  frontend:
    build:
      context: frontend
    container_name: currency-exchange-frontend
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: .
    container_name: currency-exchange-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge